#-------------------------------------------------
# ~/.bash_profile - Runs on login
# vim:foldmethod=marker:nu:ai:si:et:ft=sh:
# -------------------------------------------------

[ -f ~/.bashrc ] && . ~/.bashrc
# ssh-agent {{{1
if [ -f $SSH_AGENT_ENV ]; then
  . $SSH_AGENT_ENV > /dev/null
  if ! kill -0 $SSH_AGENT_PID > /dev/null 2>&1; then
    ssh_agent
  fi
else
  ssh_agent
fi
# 1}}}

[ -d ~/.ssh ] || exit 0


find .ssh/ -name "id_*_*" | grep -v pub | xargs ssh-add
