alias mutt-adamkosmin='MUTT_PROFILE=adamkosmin mutt'
alias mutt-mtf8='MUTT_PROFILE=mtf8 mutt'
alias mutt-nycpatriot='MUTT_PROFILE=nycpatriot mutt'
alias mutt-dstillery='MUTT_PROFILE=dstillery mutt'
alias xprop="/usr/bin/xprop | awk '/WM_CLASS/{print $4}'"
alias vip="nvim -p"
alias vid="nvim -d"
alias gs="git status -sb"
alias gl="git log --oneline"
alias grep="grep --color=auto"
# safe.sh
alias pa="safe.sh -o pass | grep"
# tmux
alias tl='tmuxp load'
alias ta='tmux attach -t'
# key-mon
alias km='key-mon --nomouse -t big-letters'
# virtualbox fix
# alias virtualbox='QT_QPA_PLATFORMTHEME=qt5ct virtualbox'
alias vbm="VBoxManage"
alias vir="virsh"
alias xeph="Xephyr -ac -noreset -screen 1024x768 :1 &"
