# vim: ft=conf
# disable bell
xset -b

# turn off screen in 20 minutes
xset dpms 1200

# no screen saver
xset s off

# kill X with ctrl+alt+backspace
setxkbmap -option terminate:ctrl_alt_bksp

# keyboard layout
setxkbmap us

# milliseconds to wait before repeating and number of repeats p/s
xset r rate 250 20

# map keys as defined
xmodmap ~/.Xmodmap

# remove mouse when idle
unclutter &

# pulse audio
start-pulseaudio-x11 &

# jackdbus starter
autojack > /tmp/autojack.log 2>&1 < /dev/null &

# composite manager
#compton -b &

# blue light
redshift-gtk &

# set mixer volume
amixer set PCM -- 95%

xsetroot -solid '#1e222a'
# load Xresources
xrdb ~/.config/astronvim/colors/xresources

# something related to font size & resolution/dpi
#WINIT_X11_SCALE_FACTOR=1

exec i3 -V > /tmp/i3.log
#exec i3 -c ~/.config/i3/config.min -V > /tmp/i3.log
