#!/usr/bin/env sh

# disable bell
xset -b

# turn off screen in 10 minutes
xset dpms 600

# no screen saver
xset s off

# kill X with ctrl+alt+backspace
setxkbmap -option terminate:ctrl_alt_bksp

# keyboard layout
setxkbmap us

# speed xrate up
xset r rate 300 50 &

# remove mouse when idle
unclutter &

# dunst for notifications
dunst &

# pulse audio
start-pulseaudio-x11 &

# jackdbus starter
autojack > /tmp/autojack.log 2>&1 < /dev/null &

# composite manager
compton -b &

# backgrounds
wal -R

# blue light
redshift-gtk &

exec i3 -V > /tmp/i3.log
# exec i3 -c ~/.config/i3/config.min -V > /tmp/i3.log
#exec startxfce4

