# If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH

# yabridge
if [ -d "$HOME/.local/share/yabridge" ]; then
  PATH="$HOME/.local/share/yabridge:$PATH"
fi

# wine with TkG patches
# export WINE_TKG_VERSION=7.0-rc1
#export WINE_TKG_VERSION=6.4
#if [ -d "$HOME/.local/share/wine-${WINE_TKG_VERSION}-staging-tkg-amd64/bin" ]; then
#  PATH="$HOME/local/share/wine-${WINE_TKG_VERSION}-staging-tkg-amd64/bin:$PATH"
#  export WINEFSYNC=1
#fi

# npm-global permissions workaround
if [ -d "$HOME/.npm-global" ]; then
  PATH="$HOME/.npm-global:$PATH"
fi

export EDITOR=nvim
export BROWSER=firefox

# Path to your oh-my-zsh installation.
export ZSH="/home/akosmin/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="oxide"
#ZSH_THEME="avit"
# ZSH_THEME="zeta"
# ZSH_THEME="celestialorb"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to automatically update without prompting.
# DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS=true

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  aws
  kube-ps1
  kubectl
  helm
  ssh-agent
  gpg-agent
  git
  zsh-autosuggestions
  zsh-syntax-highlighting
)

export ZSH_AUTOSUGGEST_STRATEGY=(history completion)
# https://github.com/ohmyzsh/ohmyzsh/issues/8336
zstyle :omz:plugins:ssh-agent agent-forwarding off

source $ZSH/oh-my-zsh.sh

PROMPT=$PROMPT'$(kube_ps1) '

# User configuration

# 3rd party here
export GOPATH=~/go
export PATH=$PATH:$GOPATH/bin

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
alias dashboard-token='kubectl -n kubernetes-dashboard describe secret dashboard-admin-token | awk "/^token/ {print $1}"'
alias dashboard-forward='kubectl -n kubernetes-dashboard port-forward svc/kubernetes-dashboard 8001:443'

. $HOME/.asdf/asdf.sh

# pywal
if [ -z "$SSH_CLIENT" ] && [ -z "$SSH_TTY" ]; then
  (cat ~/.cache/wal/sequences &)
  . ~/.cache/wal/colors-tty.sh
fi

if [ -f $HOME/.gpg-agent-info ]; then
  . $HOME/.gpg-agent-info
  export GPG_AGENT_INFO
fi

export QT_QPA_PLATFORMTHEME="qt5ct"

alias mutt-adamkosmin='MUTT_PROFILE=adamkosmin mutt'
alias mutt-mtf8='MUTT_PROFILE=mtf8 mutt'
alias mutt-nycpatriot='MUTT_PROFILE=nycpatriot mutt'
alias bt='echo 0 | gdb -batch-silent -ex "run" -ex "set logging overwrite on" -ex "set logging file gdb.bt" -ex "set logging on" -ex "set pagination off" -ex "handle SIG33 pass nostop noprint" -ex "echo backtrace:\n" -ex "backtrace full" -ex "echo \n\nregisters:\n" -ex "info registers" -ex "echo \n\ncurrent instructions:\n" -ex "x/16i \$pc" -ex "echo \n\nthreads backtrace:\n" -ex "thread apply all backtrace" -ex "set logging off" -ex "quit" --args'
alias tf="terraform"
alias kdebug="kubectl run -i --rm --tty debug --image=alpine --restart=Never -- sh"
alias yb="yabridgectl"
# if [ -e /home/akosmin/.nix-profile/etc/profile.d/nix.sh ]; then . /home/akosmin/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer

autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /home/akosmin/.asdf/installs/terraform/0.13.5/bin/terraform terraform
bindkey '^o' autosuggest-accept
