config:
  backup: true
  banner: false
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
dotfiles:
  f_xinitrc:
    src: xinitrc
    dst: ~/.xinitrc
  f_xresources:
    src: Xresources
    dst: ~/.Xresources
  f_x-color-switch.sh:
    src: bin/x-color-switch.sh
    dst: ~/bin/x-color-switch.sh
  d_xresources.d:
    src: Xresources.d
    dst: ~/.Xresources.d
  d_themes:
    src: themes
    dst: ~/.themes
  f_userchrome.css:
    src: mozilla/firefox/043ud7lz.default/chrome/userChrome.css
    dst: ~/.mozilla/firefox/043ud7lz.default/chrome/userChrome.css
  d_i3:
    src: config/i3
    dst: ~/.config/i3
  f_settings.ini:
    src: config/gtk-3.0/settings.ini
    dst: ~/.config/gtk-3.0/settings.ini
  f_redshift.conf:
    src: config/redshift/redshift.conf
    dst: ~/.config/redshift/redshift.conf
  f_systemd-optimize.sh:
    src: bin/systemd-optimize.sh
    dst: ~/bin/systemd-optimize.sh
  f_bash_prompt:
    src: bash_prompt
    dst: ~/.bash_prompt
  f_bash_aliases:
    src: bash_aliases
    dst: ~/.bash_aliases
  f_init.vim:
    src: config/nvim/init.vim
    dst: ~/.config/nvim/init.vim
  f_tmux.conf:
    src: tmux.conf
    dst: ~/.tmux.conf
  f_vimrc:
    src: vimrc
    dst: ~/.vimrc
  d_colors:
    src: vim/colors
    dst: ~/.vim/colors
  f_dir_colors:
    src: dir_colors
    dst: ~/.dir_colors
  d_termite:
    src: config/termite
    dst: ~/.config/termite
  d_rofi:
    src: config/rofi
    dst: ~/.config/rofi
  f_asoundrc:
    src: asoundrc
    dst: ~/.asoundrc
  f_bash_profile:
    src: bash_profile
    dst: ~/.bash_profile
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
  d_backgrounds:
    src: backgrounds
    dst: ~/backgrounds
profiles:
  mtf8:
    dotfiles:
    - f_xinitrc
    - f_xresources
    - f_x-color-switch.sh
    - d_xresources.d
    - d_themes
    - f_userchrome.css
    - d_i3
    - f_settings.ini
    - f_redshift.conf
    - f_systemd-optimize.sh
    - f_bash_prompt
    - f_bash_aliases
    - f_init.vim
    - f_tmux.conf
    - f_bash_profile
    - f_bashrc
    - d_backgrounds
  libretop:
    dotfiles:
    - f_vimrc
    - d_colors
    - f_dir_colors
    - d_termite
    - d_rofi
    - f_asoundrc
