config:
  backup: true
  banner: false
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
dotfiles:
  f_xinitrc:
    src: xinitrc
    dst: ~/.xinitrc
  f_xresources:
    src: Xresources
    dst: ~/.Xresources
  f_x-color-switch.sh:
    src: bin/x-color-switch.sh
    dst: ~/bin/x-color-switch.sh
  d_xresources.d:
    src: Xresources.d
    dst: ~/.Xresources.d
  d_themes:
    src: themes
    dst: ~/.themes
  d_gtk-2.0:
    src: config/gtk-2.0
    dst: ~/.config/gtk-2.0
  d_gtk-3.0:
    src: config/gtk-3.0
    dst: ~/.config/gtk-3.0
  f_userchrome.css:
    src: mozilla/firefox/043ud7lz.default/chrome/userChrome.css
    dst: ~/.mozilla/firefox/043ud7lz.default/chrome/userChrome.css
profiles:
  mtf8:
    dotfiles:
    - f_xinitrc
    - f_xresources
    - f_x-color-switch.sh
    - d_xresources.d
    - d_themes
    - d_gtk-2.0
    - d_gtk-3.0
    - f_userchrome.css
