config:
  backup: true
  banner: false
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
dotfiles:
  f_xinitrc:
    src: xinitrc
    dst: ~/.xinitrc
  f_xresources:
    src: Xresources
    dst: ~/.Xresources
    chmod: '600'
  f_x-color-switch.sh:
    src: bin/x-color-switch.sh
    dst: ~/bin/x-color-switch.sh
  d_themes:
    src: themes
    dst: ~/.themes
  f_userchrome.css:
    src: mozilla/firefox/043ud7lz.default/chrome/userChrome.css
    dst: ~/.mozilla/firefox/043ud7lz.default/chrome/userChrome.css
  d_i3:
    src: config/i3
    dst: ~/.config/i3
  f_settings.ini:
    src: config/gtk-3.0/settings.ini
    dst: ~/.config/gtk-3.0/settings.ini
  f_redshift.conf:
    src: config/redshift/redshift.conf
    dst: ~/.config/redshift/redshift.conf
  f_systemd-optimize.sh:
    src: bin/systemd-optimize.sh
    dst: ~/bin/systemd-optimize.sh
  f_init.vim:
    src: config/nvim/init.vim
    dst: ~/.config/nvim/init.vim
  f_tmux.conf:
    src: tmux.conf
    dst: ~/.tmux.conf
    chmod: '644'
  f_vimrc:
    src: vimrc
    dst: ~/.vimrc
  d_colors:
    src: vim/colors
    dst: ~/.vim/colors
  f_dir_colors:
    src: dir_colors
    dst: ~/.dir_colors
  d_termite:
    src: config/termite
    dst: ~/.config/termite
  d_rofi:
    src: config/rofi
    dst: ~/.config/rofi
  f_asoundrc:
    src: asoundrc
    dst: ~/.asoundrc
  f_bash_profile:
    src: bash_profile
    dst: ~/.bash_profile
    chmod: '644'
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
    chmod: '644'
  d_backgrounds:
    src: backgrounds
    dst: ~/backgrounds
  f_muttrc:
    src: mutt/muttrc
    dst: ~/.mutt/muttrc
    chmod: '644'
  f_256colors.muttrc:
    src: mutt/256colors.muttrc
    dst: ~/.mutt/256colors.muttrc
    chmod: '644'
  f_keys.muttrc:
    src: mutt/keys.muttrc
    dst: ~/.mutt/keys.muttrc
    chmod: '644'
  f_imap.muttrc:
    src: mutt/imap.muttrc
    dst: ~/.mutt/imap.muttrc
    chmod: '644'
  f_gpg.muttrc:
    src: mutt/gpg.muttrc
    dst: ~/.mutt/gpg.muttrc
    chmod: '644'
  f_colors:
    src: mutt/colors
    dst: ~/.mutt/colors
    chmod: '644'
  f_mutt_profile_mtf8:
    src: mutt/mutt_profile_mtf8
    dst: ~/.mutt/mutt_profile_mtf8
    chmod: '644'
  f_mutt_profile_mtf8.sig:
    src: mutt/mutt_profile_mtf8.sig
    dst: ~/.mutt/mutt_profile_mtf8.sig
    chmod: '644'
  f_mutt_profile_adamkosmin:
    src: mutt/mutt_profile_adamkosmin
    dst: ~/.mutt/mutt_profile_adamkosmin
    chmod: '644'
  f_mutt_profile_adamkosmin.sig:
    src: mutt/mutt_profile_adamkosmin.sig
    dst: ~/.mutt/mutt_profile_adamkosmin.sig
    chmod: '644'
  f_mutt_profile_nycpatriot:
    src: mutt/mutt_profile_nycpatriot
    dst: ~/.mutt/mutt_profile_nycpatriot
    chmod: '644'
  f_mutt_profile_nycpatriot.sig:
    src: mutt/mutt_profile_nycpatriot.sig
    dst: ~/.mutt/mutt_profile_nycpatriot.sig
    chmod: '644'
  f_monitor.sh:
    src: bin/monitor.sh
    dst: ~/bin/monitor.sh
    chmod: '744'
  f_saferc:
    src: saferc
    dst: ~/.saferc
  d_tmuxp:
    src: tmuxp
    dst: ~/.tmuxp
  f_vimrc-basic:
    src: vimrc-basic
    dst: ~/.vimrc-basic
  f_config:
    src: config/vis/config
    dst: ~/.config/vis/config
  d_vis_colors:
    src: config/vis/colors
    dst: ~/.config/vis/colors
  f_mopidy.conf:
    src: config/mopidy/mopidy.conf
    dst: ~/.config/mopidy/mopidy.conf
  f_ncmpcpp_config:
    src: ncmpcpp/config
    dst: ~/.ncmpcpp/config
  f_lab-kvm.sh:
    src: bin/lab-kvm.sh
    dst: ~/bin/lab-kvm.sh
    chmod: '764'
  f_ssh_config:
    src: ssh/config
    dst: ~/.ssh/config
    chmod: '644'
  f_inputrc:
    src: inputrc
    dst: ~/.inputrc
  f_alacritty.yml:
    src: config/alacritty/alacritty.yml
    dst: ~/.config/alacritty/alacritty.yml
  f_xmodmap:
    src: Xmodmap
    dst: ~/.Xmodmap
  f_tmuxline.conf:
    src: tmux/tmuxline.conf
    dst: ~/.tmux/tmuxline.conf
  d_bashrc.d:
    src: bashrc.d
    dst: ~/.bashrc.d
  f_settings.vim:
    src: config/nvim/settings.vim
    dst: ~/.config/nvim/settings.vim
  f_vim-plug.vim:
    src: config/nvim/vim-plug.vim
    dst: ~/.config/nvim/vim-plug.vim
  f_mappings.vim:
    src: config/nvim/mappings.vim
    dst: ~/.config/nvim/mappings.vim
  d_plug-config:
    src: config/nvim/plug-config
    dst: ~/.config/nvim/plug-config
  f_coc.vim:
    src: config/nvim/plug-config/coc.vim
    dst: ~/.config/nvim/plug-config/coc.vim
  f_lightline.vim:
    src: config/nvim/plug-config/lightline.vim
    dst: ~/.config/nvim/plug-config/lightline.vim
  f_colors-rofi-dark.rasi:
    src: config/wal/templates/colors-rofi-dark.rasi
    dst: ~/.config/wal/templates/colors-rofi-dark.rasi
  f_config.rasi:
    src: config/rofi/config.rasi
    dst: ~/.config/rofi/config.rasi
  f_sequences:
    src: cache/wal/sequences
    dst: ~/.cache/wal/sequences
profiles:
  mtf8:
    dotfiles:
    - f_xinitrc
    - f_xresources
    - f_x-color-switch.sh
    - d_themes
    - f_userchrome.css
    - d_i3
    - f_settings.ini
    - f_redshift.conf
    - f_systemd-optimize.sh
    - f_init.vim
    - f_tmux.conf
    - f_bash_profile
    - f_bashrc
    - d_backgrounds
    - f_muttrc
    - f_256colors.muttrc
    - f_keys.muttrc
    - f_imap.muttrc
    - f_gpg.muttrc
    - f_colors
    - f_mutt_profile_mtf8
    - f_mutt_profile_mtf8.sig
    - f_mutt_profile_adamkosmin
    - f_mutt_profile_adamkosmin.sig
    - f_mutt_profile_nycpatriot
    - f_mutt_profile_nycpatriot.sig
    - f_monitor.sh
    - f_dir_colors
    - d_tmuxp
    - f_vimrc-basic
    - f_config
    - d_vis_colors
    - f_mopidy.conf
    - f_ncmpcpp_config
    - f_lab-kvm.sh
    - f_ssh_config
    - f_inputrc
    - f_alacritty.yml
    - f_xmodmap
    - f_tmuxline.conf
    - d_bashrc.d
    - f_settings.vim
    - f_vim-plug.vim
    - f_mappings.vim
    - d_plug-config
    - f_coc.vim
    - f_lightline.vim
    - f_colors-rofi-dark.rasi
    - f_config.rasi
    - f_sequences
  libretop:
    dotfiles:
    - f_vimrc
    - d_colors
    - f_dir_colors
    - d_termite
    - d_rofi
    - f_asoundrc
  dstiltop:
    dotfiles:
    - f_saferc
