import:
  - ~/.config/astronvim/colors/alacritty

env:
  # TERM variable
  #
  # This value is used to set the `$TERM` environment variable for
  # each instance of Alacritty. If it is not present, alacritty will
  # check the local terminfo database and use `alacritty` if it is
  # available, otherwise `xterm-256color` is used.
  TERM: xterm-256color

font:
  # Normal (roman) font face
  normal:
    family: Hack
    style: Regular

  # Bold font face
  bold:
    family: Hack
    style: Bold

  # Italic font face
  italic:
    family: Hack
    style: Italic

  # Bold italic font face
  bold_italic:
    family: Hack
    style: Bold Italic

  # Point size
  size: 14.0

  offset:
    x: 0
    y: 0

  glyph_offset:
    x: 0
    y: 0

# background_opacity: 1.0

# Live config reload (changes require restart)
live_config_reload: true

mouse:
  # Click settings
  #
  # The `double_click` and `triple_click` settings control the time
  # alacritty should wait for accepting multiple clicks as one double
  # or triple click.
  #double_click: { threshold: 300 }
  #triple_click: { threshold: 300 }

  # If this is `true`, the cursor is temporarily hidden when typing.
  hide_when_typing: true

  #url:
  # URL launcher
  #
  # This program is executed when clicking on a text which is recognized as a URL.
  # The URL is always added to the command as the last parameter.
  #
  # When set to `None`, URL launching will be disabled completely.
  #
  # Default:
  #   - (macOS) open
  #   - (Linux/BSD) xdg-open
  #   - (Windows) explorer
  #launcher:
  #  program: xdg-open
  #  args: []
  # URL modifiers
  #
  # These are the modifiers that need to be held down for opening URLs when clicking
  # on them. The available modifiers are documented in the key binding section.
  #modifiers: None

key_bindings:
  - { key: V, mods: Control|Shift, action: Paste }
  - { key: C, mods: Control|Shift, action: Copy }
  - { key: Key0, mods: Control, action: ResetFontSize }
  - { key: Equals, mods: Control, action: IncreaseFontSize }
  - { key: Minus, mods: Control, action: DecreaseFontSize }

scrolling:
  history: 10000

selection:
  save_to_clipboard: true
window:
  padding:
    x: 5
    y: 8
  # decorations: "none"
