#!/bin/bash

set_prompt()
{
   local txtreset='$(tput sgr0)'
   local txtbold='$(tput bold)'
   local txtblack='$(tput setaf 0)'
   local txtred='$(tput setaf 1)'
   local txtgreen='$(tput setaf 2)'
   local txtyellow='$(tput setaf 3)'
   local txtblue='$(tput setaf 4)'
   local txtpurple='$(tput setaf 5)'
   local txtcyan='$(tput setaf 6)'
   local txtwhite='$(tput setaf 7)'
   # Line 1: newline
   PS1="\n"
   # Line 2: user@host:$CWD (git status)
   PS1+="\[$txtgreen\]\h:\[$txtyellow\]\w\[$txtpurple\]$(__git_ps1 ' (%s)')\[$txtcyan\] $(kube_ps1)\[$txtwhite\]\n"
   # Line 3: a red or green > depending on return status
   if [[ $? == 0 ]]; then
      PS1+="\[$txtgreen\]"
   else
      PS1+="\[$txtred\]"
   fi
   PS1+="> \[$txtwhite\]"
}
PROMPT_COMMAND='set_prompt'
